version: '3.8'

services:
  web_tools:
    build:
      context: .
      dockerfile: Dockerfile
    image: web_tools:latest
    container_name: web_tools
    volumes:
      - ./workspace:/home/webuser/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/home/webuser/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/webuser/.Xauthority
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true
    user: 1000:1000